### ISSUE TITLE
[BUG] Only a maximum of 1000 transactions are displayed

### ISSUE THREAD

**Issue by songgeng87** [harmony-one/harmony-dashboard#94] opened 2020-05-19 09:17 UTC
https://explorer.harmony.one/#/address/one1wx6p8kjucu5llqz79h9pmn0qf55772m2d2xt26

for example, this address one1wx6p8kjucu5llqz79h9pmn0qf55772m2d2xt26

**Comment by mindstyle85** [comment] 2020-06-05 12:45
@denniswon @potvik @LeoHChen this is really a priority issue imo, lots of validators and partners cant even check latest txs on explorer due to the maximum cap hit. If you cant display all, i propose an "archive" link which would give you full history, and display only the latest X txs there..

honest mining for example, didnt even hit 1k and they dont see any txs after 05/28... https://explorer.harmony.one/#/address/one1dtrl3pvd9cfr6vgn6k5sdc7fwvk9p9hqn0gg0q?txType=regular

**Comment by potvik** [comment] 2020-06-05 14:11
Frontend part done - https://github.com/harmony-one/harmony-dashboard/pull/95

**Comment by denniswon** [comment] 2020-06-26 10:56
@potvik api should be updated. Refer to my comment made in https://github.com/harmony-one/harmony-dashboard/issues/89.

Closing this issue as it is a duplicate of https://github.com/harmony-one/harmony-dashboard/issues/89

**Closed by denniswon** 2020-06-26 10:56 UTC
Labels: high priority
